import './globals.css'
import Header from './components/header'
import { AuthProvider } from '@/services/authContext'
import {OtherProvider} from '@/services/otherContext'
import {UserProvider} from '@/services/userContext'



export const metadata = {
  title: 'SystemOS',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children, 
}: {
  children: React.ReactNode
}) {
  
  return (    
    <html lang="en">
      <body>
        <AuthProvider>
          <OtherProvider>
            <UserProvider>
              {children}
              <Header/>
            </UserProvider>
          </OtherProvider>
        </AuthProvider>
      </body>
    </html>
  )
}
